apiVersion: v1
kind: Secret
metadata:
  name: learnlab-secrets
  labels:
    app.kubernetes.io/name: learnlab
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # base64-encoded secrets (replace in CI/CD)
  API_KEY: {{ "change-me" | b64enc }}
  JWT_SECRET: {{ "change-me" | b64enc }}
